version: 2
builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    ldflags:
      - -s -w
      - -X main.version={{.Version}} -X main.commit={{.Commit}}
      - -X main.shouldLog=false
    env:
      - CGO_ENABLED=0
    overrides:
      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=1

archives:
  - formats: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  draft: true
  replace_existing_draft: true